# *****************************************************************************
# File Name: Dockerfile_matery
# Auther: Chuncheng Wei
# Email: weicc1989@gmail.com
# Created Time: Fri Nov 30 23:08:07 2018
# Description:
#
#     This bases on node:10 image
#
# *****************************************************************************


# 基础镜像
FROM hexo:10

# 维护者信息
MAINTAINER Chuncheng_Wei <weicc1989@gmail.com>

# 工作目录
WORKDIR /hexo

# 安装Hexo插件
RUN npm i -S hexo-prism-plugin
RUN npm install hexo-generator-search --save
RUN npm i hexo-permalink-pinyin --save
RUN npm install hexo-generator-feed --save
RUN npm install hexo-deployer-git --save

# 挂载volume
VOLUME ["/hexo/.deploy_git", "/hexo/scaffolds", "/hexo/source", "/hexo/themes", "/root/.ssh"]

# 映射端口
EXPOSE 4000

# 运行命令
CMD ["/usr/bin/env", "hexo", "server"]
